'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/app/ui/nav';
import React, { useState, useEffect } from 'react';
import {
  RecoilRoot,
  atom,
  selector,
  useRecoilState,
  useRecoilValue,
} from 'recoil';
import { userState } from './lib/atoms';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
function AppState(){
  const [user, setUserState] = useRecoilState(userState)
  
  useEffect(()  => {
    // 컴포넌트가 언마운트될 때 이벤트 리스너 제거
    const tokensString = localStorage.getItem('TIKTAKA');
    const tokens = tokensString ? JSON.parse(tokensString) : null
    const accessToken = tokens ? tokens.access : null
    function parseJwt(token: string) {
      if (!token) { return; }
      const base64Url = token.split('.')[1];
      const base64 = base64Url.replace('-', '+').replace('_', '/');
      return JSON.parse(atob(base64));
    }
    if (accessToken){
      const userState = parseJwt(accessToken);
      console.log(userState, 'usersss', Math.floor(Date.now() / 1000) - 1705824154);
      setUserState({
        ...user,
        user_id: userState.user_id,
        username: userState.username
      })
    };
  }, []);
  return <></>
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {  
  return (
    <html lang='en'>
      <head>
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </head>
      <body>
      <RecoilRoot>
        <AppState />
        {children}
        <Navbar />
      </RecoilRoot>
      </body>
    </html>
  );
}
